---
- name: Install required packages
  become: yes
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Install additional pacakges for Ubuntu 14.04
  become: yes
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - "linux-image-extra-{{ ansible_kernel }}"
    - "linux-image-extra-virtual"
  when: ansible_distribution_version == 14.04

- name: Add docker's official GPG key to apt
  become: yes
  apt_key:
    url: "{{ docker_key_server }}"
    state: present

- name: Add Docker's apt repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install docker CE
  become: yes
  apt:
    pkg: "docker-ce"
    state: latest
    update_cache: yes

- name: Upgrade pip
  become: true
  pip:
    name: pip
    state: latest

- name: Install python docker
  become: true
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker
    - docker-py

- name: Add user to docker group
  become: true
  user:
    name: "{{ ansible_ssh_user }}"
    groups: "docker"
